### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by R3pl4c3r**

### CODE REVIEW

**Review by VojtechVitek — APPROVED** [review]
LGTM.

--

*Side note:*

@R3pl4c3r were you able to generate the .ipk package? The `1.7.1-fix` binary requires libssl@1.0 and libcrypto@1.0 and both are not available in the latest stable OpenWRT anymore.

```
Error loading shared library libcrypto.so.1.0.0: No such file or directory (needed by /usr/sbin/openfortivpn)
Error loading shared library libssl.so.1.0.0: No such file or directory (needed by /usr/sbin/openfortivpn)
```

So I wonder if this PR fixes this too.

*EDIT:* I solved this by downloading older OpenWrt 18.06.8's libopenssl package. Warning for others: Installing older SSL is not the greatest idea from the security point of view. Be cautious.
```
wget https://downloads.openwrt.org/releases/18.06.8/packages/mips_24kc/base/libopenssl_1.0.2u-1_mips_24kc.ipk
```

**Comment by R3pl4c3r** [comment]
@VojtechVitek Sorry about that, I am not able to solve this  problem, since the older version is used in the upstream repository.

**Comment by VojtechVitek** [comment]
@R3pl4c3r no need to apologize. Your contribution looks good. Thanks!

**Comment by VojtechVitek** [comment]
FYI, I found much newer package at https://downloads.openwrt.org/snapshots/packages/mips_24kc/packages/openfortivpn_1.15.0-1_mips_24kc.ipk. I'm not sure if this is related to this repo or not.

**Comment by R3pl4c3r** [comment]
> FYI, I found much newer package at https://downloads.openwrt.org/snapshots/packages/mips_24kc/packages/openfortivpn_1.15.0-1_mips_24kc.ipk. I'm not sure if this is related to this repo or not.

@VojtechVitek It can't be this repo. The ipk's name of this repo should be openfortivpn_1.15.0_git3378911-1_xxx.ipk. Apart from that, my pr hasn't been merged, so it can’t relate to this repo. And I am sure there is another openfortivpn repo for openwrt.

**Comment by R3pl4c3r** [comment]
@VojtechVitek Ah, I found it: https://github.com/openwrt/packages/tree/master/net/openfortivpn
So this is outdated repo and we should use official the latest repo.

**Pull request closed without merging**
